spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2000cyf0529
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=FALSE&serverTimezone=UTC&rewriteBatchedStatements=true
server:
  port: 8080
jpa:
  hibernate:
    ddl-auto: none
  show-sql: true
